// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as ConversationTable } from './Conversation';
import { type default as MessageTable } from './Message';

export default interface PublicSchema {
  Conversation: ConversationTable;

  Message: MessageTable;
}
